# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Jenkins
description:  My name is Chris. I have a background in agriculture and computer science.
              I'm a software engineer, thinker, and tinkerer. I'll post here original 
              ideas and interesting things, along with what I'm learning and want to
              remember.
url: "http://cajenkins.com" # the base hostname & protocol for your site
github_username:  hadibus

# Build settings
markdown: kramdown
